# Generated by Django 6.0.5 on 2026-06-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystem', '0004_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('substitute', models.CharField(max_length=100)),
                ('similarity', models.IntegerField(default=100)),
            ],
        ),
    ]
