# Generated by Django 6.0.5 on 2026-06-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystem', '0005_ingredientsubstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('fat', models.FloatField()),
            ],
        ),
    ]
