# Generated by Django 6.0.5 on 2026-06-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystem', '0006_ingredientnutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(),
        ),
    ]
