# Generated by Django 6.0.5 on 2026-07-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsystem', '0008_delete_ingredientnutrition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='used_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
